
--1. How many total orders has UrbanCart received so far?

SELECT
COUNT(*) AS "Total Number of Orders"
FROM public."FactOrders"

-- 2.How many unique customers have placed at least one order?

SELECT 
COUNT(DISTINCT customer_id) AS "Amount of Unique Customers"
FROM public."FactOrders"

-- 3.Which cities generate the highest number of orders?

SELECT 
    c.city,  
    COUNT(o.order_id) AS "Total Orders"
FROM public."FactOrders" as o
JOIN "DimCustomers" as c ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY "Total Orders" DESC
Limit 9


-- 4. What percentage of customers have placed more than one order?

WITH CustomerOrderCounts AS (
  SELECT 
    customer_id,
    COUNT(DISTINCT order_id) AS order_count
  FROM public."FactOrders"
  GROUP BY customer_id
)
SELECT
  ROUND((COUNT(CASE WHEN order_count > 1 THEN 1 END) * 100.0) / COUNT(*),2) AS percentage_more_than_one_order
FROM CustomerOrderCounts


-- 5. What is the monthly trend of total orders over time?

SELECT 
  TO_CHAR(TO_DATE(fo.order_date, 'MM/DD/YYYY'), 'FMMonth') AS month_name,  
  COUNT(fo.order_id) AS total_orders
FROM public."FactOrders" fo
GROUP BY TO_CHAR(TO_DATE(fo.order_date, 'MM/DD/YYYY'), 'FMMonth')  
ORDER BY MIN(TO_DATE(fo.order_date, 'MM/DD/YYYY')) ASC


-- 6.What is the total revenue generated by UrbanCart?

-- on completed orders

WITH completed_orders AS (
  SELECT oi.*, o.status
  FROM public."FactOrderItems" oi
  LEFT JOIN public."FactOrders" o 
    ON o.order_id = oi.order_id
  WHERE o.status = 'Completed'  -- Ensure only completed orders are considered
)
, individual_rev AS (
  SELECT co.*, p.unit_price, co.quantity * p.unit_price AS rev
  FROM completed_orders co
  LEFT JOIN public."DimProducts" p 
    ON co.product_id = p.product_id
)
SELECT SUM(rev) AS total_revenue
FROM individual_rev

-- on pending orders

WITH pending_orders AS (
  SELECT oi.*, o.status
  FROM public."FactOrderItems" oi
  LEFT JOIN public."FactOrders" o 
    ON o.order_id = oi.order_id
  WHERE o.status IN ('Completed', 'Pending')  -- both 'Completed' and 'Pending'
)
, individual_rev AS (
  SELECT co.*, p.unit_price, co.quantity * p.unit_price AS rev
  FROM pending_orders co
  LEFT JOIN public."DimProducts" p 
    ON co.product_id = p.product_id
)
SELECT SUM(rev) AS total_revenue 
FROM individual_rev

-- 7.Which product categories contribute the most to total revenue?

SELECT 
  dp.category,
  SUM(foi.quantity * dp.unit_price) AS total_revenue
FROM public."FactOrderItems" foi
JOIN public."DimProducts" dp ON foi.product_id = dp.product_id
JOIN public."FactOrders" fo ON foi.order_id = fo.order_id
WHERE fo.status = 'Completed'  -- Exclude canceled or returned orders
GROUP BY dp.category
ORDER BY total_revenue DESC
LIMIT 8


-- 8.Which individual products generate the highest revenue?

SELECT 
  dp.product_name,
  SUM(foi.quantity * dp.unit_price) AS total_revenue
FROM public."FactOrderItems" foi
JOIN public."DimProducts" dp ON foi.product_id = dp.product_id
JOIN public."FactOrders" fo ON foi.order_id = fo.order_id
WHERE fo.status = 'Completed'  -- Exclude canceled or returned orders
GROUP BY dp.product_name
ORDER BY total_revenue DESC
LIMIT 10

--9.What is the average order value (AOV) and Average Basket Size?

SELECT
	ROUND(SUM(foi.quantity * dp.unit_price) / COUNT(DISTINCT fo.order_id),2) AS average_order_value,
	ROUND(SUM (foi.quantity) / COUNT(DISTINCT fo.order_id),2) AS Average_Basket_Size
FROM public."FactOrders" fo
JOIN "FactOrderItems" foi on foi.order_id = fo.order_id
JOIN "DimProducts" dp on dp.product_id = foi.product_id

-- 10. Which products are at risk of stock-out due to high sales volume and low inventory?

SELECT 
  dp.product_name,
  SUM(foi.quantity) AS total_sales_volume, 
  (dp.stock - SUM(foi.quantity)) AS stock_difference,
  CASE
    WHEN dp.stock < SUM(foi.quantity) THEN 'at_risk'
    ELSE 'Stock Sufficient'
  END AS stock_status,
  ROUND(CAST(dp.stock AS NUMERIC) / NULLIF(SUM(foi.quantity), 0), 2) AS stock_ratio  
FROM public."FactOrderItems" foi
JOIN public."DimProducts" dp ON foi.product_id = dp.product_id
JOIN public."FactOrders" fo ON foi.order_id = fo.order_id
WHERE fo.status = 'Completed'  
GROUP BY dp.product_name, dp.stock
ORDER BY stock_difference ASC 
LIMIT 15

--11.Which customers contribute the highest total revenue?

SELECT 
  c.customer_id,             
  c.full_name,           
  SUM(foi.quantity * dp.unit_price) AS total_revenue
FROM public."FactOrders" fo
JOIN "FactOrderItems" foi ON foi.order_id = fo.order_id
JOIN "DimProducts" dp ON foi.product_id = dp.product_id
LEFT JOIN public."DimCustomers" c ON c.customer_id = fo.customer_id  
GROUP BY c.customer_id, c.full_name  
ORDER BY total_revenue DESC
LIMIT 15

-- 12.What is the average number of products purchased per order?

SELECT 
  ROUND(SUM(foi.quantity) / COUNT(DISTINCT fo.order_id),3) AS avg_products_per_order
FROM public."FactOrderItems" foi
JOIN public."FactOrders" fo ON foi.order_id = fo.order_id

-- 13.Do male and female customers show different purchasing patterns by category?

WITH ct AS (
  SELECT 
    foi.order_id,
    foi.product_id,
    foi.quantity,
    dp."category",
    fo.customer_id,
    dc."Gender",
    fo.status
  FROM public."FactOrderItems" foi
  LEFT JOIN "DimProducts" dp ON foi.product_id = dp.product_id
  LEFT JOIN "FactOrders" fo ON fo.order_id = foi.order_id
  LEFT JOIN public."DimCustomers" dc ON fo.customer_id::bigint = dc.customer_id
  WHERE fo.status IN ('Completed', 'Pending') 
)
SELECT 
  ct.category,
  SUM(CASE WHEN ct."Gender" = 'Male' THEN ct.quantity ELSE 0 END) AS Quantity_of_Male,
  SUM(CASE WHEN ct."Gender" = 'Female' THEN ct.quantity ELSE 0 END) AS Quantity_of_Female
FROM ct  -- Reference the CTE here
GROUP BY ct.category  
ORDER BY ct.category

-- 14.Which cities have the highest average order value?

SELECT 
  dc.city, 
  ROUND(SUM(foi.quantity * dp.unit_price) / COUNT(DISTINCT fo.order_id),2) AS avg_order_value
FROM public."FactOrders" fo
JOIN public."FactOrderItems" foi ON foi.order_id = fo.order_id
JOIN public."DimProducts" dp ON dp.product_id = foi.product_id
JOIN public."DimCustomers" dc ON dc.customer_id = fo.customer_id
GROUP BY dc.city
ORDER BY avg_order_value DESC

-- 15.How does customer purchasing behavior change over time since account creation?

SELECT 
  dc.city, 
  dc."created_at",
  EXTRACT(MONTH FROM AGE(CURRENT_DATE, TO_DATE(dc."created_at", 'MM/DD/YYYY'))) AS months_since_creation, 
  COUNT(DISTINCT fo.order_id) AS total_orders,
  SUM(foi.quantity * dp.unit_price) AS total_revenue,
  ROUND (SUM(foi.quantity * dp.unit_price) / COUNT(DISTINCT fo.order_id),2) AS avg_order_value
FROM public."FactOrders" fo
JOIN public."FactOrderItems" foi ON foi.order_id = fo.order_id
JOIN public."DimProducts" dp ON dp.product_id = foi.product_id
JOIN public."DimCustomers" dc ON dc.customer_id = fo.customer_id
GROUP BY dc.city, dc."created_at", months_since_creation
ORDER BY months_since_creation, total_revenue, avg_order_value DESC
LIMIT 10

-- 16.Which payment methods are used most frequently?

Select
fp.method,
	COUNT (fp.payment_id) as Payment_Count
FROM public."FactPayment" fp
Group By fp.method
Order By Payment_Count desc

-- 17.Is there any relationship between payment method and order status?

SELECT
  fp.method AS Payment_Method,
  COUNT(CASE WHEN fo.status = 'Completed' THEN 1 END) AS Completed_Orders,
  COUNT(CASE WHEN fo.status = 'Cancelled' THEN 1 END) AS Cancelled_Orders,
  COUNT(CASE WHEN fo.status = 'Pending' THEN 1 END) AS Pending_Orders
FROM public."FactPayment" fp
JOIN public."FactOrders" fo ON fo.order_id = fp.order_id
WHERE fo.status IN ('Completed', 'Cancelled', 'Pending')  -- Filter for these statuses only
GROUP BY fp.method
ORDER BY Payment_Method

--18.Do certain cities prefer specific payment methods?

SELECT 
  dc.city, 
  SUM(CASE WHEN fp.method = 'Debit Card' THEN 1 ELSE 0 END) AS debit_card,
  SUM(CASE WHEN fp.method = 'COD' THEN 1 ELSE 0 END) AS cod,
  SUM(CASE WHEN fp.method = 'Credit Card' THEN 1 ELSE 0 END) AS credit_card,
  SUM(CASE WHEN fp.method = 'bKash' THEN 1 ELSE 0 END) AS bkash,
  SUM(CASE WHEN fp.method = 'Nagad' THEN 1 ELSE 0 END) AS nagad
FROM public."FactOrders" fo
JOIN "FactPayment" fp ON fo.order_id = fp.order_id
JOIN "DimCustomers" dc ON fo.customer_id = dc.customer_id
WHERE fo.status IN ('Completed', 'Pending')  
GROUP BY dc.city
ORDER BY dc.city

-- 19.Are higher-value orders associated with specific payment methods?

SELECT 
  fp.method AS payment_method,
  Round(AVG(foi.quantity * dp.unit_price),2) AS avg_order_value
FROM public."FactOrders" fo
JOIN public."FactOrderItems" foi ON foi.order_id = fo.order_id
JOIN public."DimProducts" dp ON dp.product_id = foi.product_id
JOIN public."FactPayment" fp ON fp.order_id = fo.order_id
GROUP BY fp.method
ORDER BY avg_order_value DESC

-- 20.What is the average number of items per order by payment method?

SELECT 
  fp.method AS payment_method,
  ROUND(SUM(foi.quantity) / COUNT(DISTINCT fo.order_id),2) AS avg_items_per_order
FROM public."FactOrders" fo
JOIN public."FactOrderItems" foi ON foi.order_id = fo.order_id
JOIN public."FactPayment" fp ON fp.order_id = fo.order_id
GROUP BY fp.method
ORDER BY avg_items_per_order DESC

-- 21.Which products are most frequently ordered together?

WITH ProductPairs AS (
  SELECT 
    foi1.order_id,
    foi1.product_id AS product_1_id,
    foi2.product_id AS product_2_id
  FROM public."FactOrderItems" foi1
  JOIN public."FactOrderItems" foi2 
    ON foi1.order_id = foi2.order_id 
    AND foi1.product_id < foi2.product_id 
)
SELECT 
  p1.product_id AS product_1_id,
  p1.product_name AS product_1,
  p2.product_id AS product_2_id,
  p2.product_name AS product_2,
  COUNT(*) AS times_ordered_together
FROM ProductPairs pp
JOIN public."DimProducts" p1 ON p1.product_id = pp.product_1_id
JOIN public."DimProducts" p2 ON p2.product_id = pp.product_2_id
GROUP BY p1.product_id, p1.product_name, p2.product_id, p2.product_name
ORDER BY times_ordered_together DESC
LIMIT 10

-- 22.Which product pairs appear most often across all orders?

WITH ProductPairs AS (
  SELECT 
    foi1.order_id,
    foi1.product_id AS product_1_id,
    foi2.product_id AS product_2_id
  FROM public."FactOrderItems" foi1
  JOIN public."FactOrderItems" foi2 
    ON foi1.order_id = foi2.order_id 
    AND foi1.product_id < foi2.product_id 
)
SELECT 
  p1.product_id AS product_1_id,
  p1.product_name AS product_1,
  p2.product_id AS product_2_id,
  p2.product_name AS product_2,
  COUNT(*) AS times_ordered_together
FROM ProductPairs pp
JOIN public."DimProducts" p1 ON p1.product_id = pp.product_1_id
JOIN public."DimProducts" p2 ON p2.product_id = pp.product_2_id
GROUP BY p1.product_id, p1.product_name, p2.product_id, p2.product_name
ORDER BY times_ordered_together DESC
LIMIT 10

-- 23.Are there product pairs that consistently drive higher order values?

WITH ProductPairs AS (
  SELECT 
    foi1.order_id,
    foi1.product_id AS product_1_id,
    foi2.product_id AS product_2_id,
    SUM(foi1.quantity * dp1.unit_price + foi2.quantity * dp2.unit_price) AS total_order_value
  FROM public."FactOrderItems" foi1
  JOIN public."FactOrderItems" foi2 
    ON foi1.order_id = foi2.order_id 
    AND foi1.product_id < foi2.product_id  
  JOIN public."DimProducts" dp1 ON dp1.product_id = foi1.product_id
  JOIN public."DimProducts" dp2 ON dp2.product_id = foi2.product_id
  GROUP BY foi1.order_id, foi1.product_id, foi2.product_id
)
SELECT 
  p1.product_name AS product_1,
  p2.product_name AS product_2,
  COUNT(*) AS co_occurrence_count,
  Round(AVG(pp.total_order_value),2) AS avg_order_value
FROM ProductPairs pp
JOIN public."DimProducts" p1 ON p1.product_id = pp.product_1_id
JOIN public."DimProducts" p2 ON p2.product_id = pp.product_2_id
GROUP BY p1.product_name, p2.product_name
ORDER BY avg_order_value DESC, co_occurrence_count DESC
LIMIT 10

-- 24.Which product combinations could be recommended as bundles to increase revenue?

WITH ProductPairs AS (
  SELECT 
    foi1.order_id,
    foi1.product_id AS product_1_id,
    foi2.product_id AS product_2_id,
    SUM(foi1.quantity * dp1.unit_price + foi2.quantity * dp2.unit_price) AS total_order_value
  FROM public."FactOrderItems" foi1
  JOIN public."FactOrderItems" foi2 
    ON foi1.order_id = foi2.order_id 
    AND foi1.product_id < foi2.product_id  
  JOIN public."DimProducts" dp1 ON dp1.product_id = foi1.product_id
  JOIN public."DimProducts" dp2 ON dp2.product_id = foi2.product_id
  GROUP BY foi1.order_id, foi1.product_id, foi2.product_id
)
SELECT 
  p1.product_name AS product_1,
  p2.product_name AS product_2,
  COUNT(*) AS co_occurrence_count,
  ROUND(AVG(pp.total_order_value),2) AS avg_order_value,
  SUM(pp.total_order_value) AS total_pair_revenue
FROM ProductPairs pp
JOIN public."DimProducts" p1 ON p1.product_id = pp.product_1_id
JOIN public."DimProducts" p2 ON p2.product_id = pp.product_2_id
GROUP BY p1.product_name, p2.product_name
ORDER BY co_occurrence_count DESC, avg_order_value DESC, total_pair_revenue DESC
LIMIT 15


-- 25.Based on product co-occurrence and customer behavior, which
-- products should UrbanCart promote together to maximize cross-selling opportunities?

WITH ProductPairs AS (
  SELECT 
    foi1.order_id,
    foi1.product_id AS product_1_id,
    foi2.product_id AS product_2_id,
    SUM(foi1.quantity * dp1.unit_price + foi2.quantity * dp2.unit_price) AS total_order_value
  FROM public."FactOrderItems" foi1
  JOIN public."FactOrderItems" foi2 
    ON foi1.order_id = foi2.order_id 
    AND foi1.product_id < foi2.product_id 
  JOIN public."DimProducts" dp1 ON dp1.product_id = foi1.product_id
  JOIN public."DimProducts" dp2 ON dp2.product_id = foi2.product_id
  GROUP BY foi1.order_id, foi1.product_id, foi2.product_id
)
SELECT 
  p1.product_name AS product_1,
  p2.product_name AS product_2,
  COUNT(*) AS co_occurrence_count,
  SUM(pp.total_order_value) AS pair_revenue  
FROM ProductPairs pp
JOIN public."DimProducts" p1 ON p1.product_id = pp.product_1_id
JOIN public."DimProducts" p2 ON p2.product_id = pp.product_2_id
GROUP BY p1.product_name, p2.product_name
ORDER BY pair_revenue DESC, co_occurrence_count DESC
LIMIT 15



